# clusters/landesamt-ds/rancher-monitoring/values.yaml

global:
  cattle:
    clusterName: landesamt-ds  # ¡Muy importante! Esto debe coincidir con el nombre del cluster en Rancher

prometheus:
  prometheusSpec:
    retention: 1d
    replicas: 1
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: null
          accessModes: []
          resources: {}

alertmanager:
  alertmanagerSpec:
    replicas: 1
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: null
          accessModes: []
          resources: {}

grafana:
  persistence:
    enabled: false

# Deshabilitar webhooks si el cluster no los necesita
prometheusOperator:
  admissionWebhooks:
    enabled: false

# Node Exporter (puedes dejarlo activado si quieres métricas de nodos)
# Si el cluster es muy pequeño, puedes desactivarlo:
# nodeExporter:
#   enabled: false

windowsExporter:
  enabled: false
